version: 2.1

orbs:
  android: circleci/android@2.5.0  # Use the Android Orb

jobs:
  build-and-test:
    executor: android/android  # Use the Android executor
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - android/gradle-cache  # Cache Gradle dependencies
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Run Gradle tasks
          command: ./gradlew assembleDebug test
      - store_test_results:
          path: app/build/test-results  # Update this path according to your project structure
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
      - store_artifacts:
          path: app/build/outputs  # Update this path according to your project structure

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test

