version: 2.1

orbs:
  android: circleci/android@2.5.0  # Ensure you're using the latest version

jobs:
  build-and-test:
    executor: android/android-machine
    steps:
      - checkout
      - restore_cache:  # Restore cached dependencies
          keys:
            - gradle-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Run Gradle tasks
          command: ./gradlew assembleDebug test
      - save_cache:  # Cache dependencies
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test

